# Generated by Django 5.0.6 on 2024-06-26 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
        (
            "store",
            "0013_alter_productimage_options_product__attributes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "date_start",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата начала демонстрации",
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата завершение демонстрации",
                    ),
                ),
                (
                    "is_on_all_pages",
                    models.BooleanField(
                        default=False,
                        verbose_name="Показывать на всех страницах",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Статус"),
                ),
                (
                    "_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="_catalog_banners",
                        to="store.catalog",
                    ),
                ),
                (
                    "catalog_desktop_image",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="images.image",
                        verbose_name="Изображение в каталоге (Desktop)",
                    ),
                ),
                (
                    "catalog_mobile_image",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="images.image",
                        verbose_name="Изображение в каталоге (Mobile)",
                    ),
                ),
                (
                    "header_desktop_image",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="images.image",
                        verbose_name="Изображение в шапке",
                    ),
                ),
                (
                    "home_desktop_image",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="images.image",
                        verbose_name="Изображение на главной (Desktop)",
                    ),
                ),
                (
                    "home_mobile_image",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="images.image",
                        verbose_name="Изображение на главной (Mobile)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Баннер",
                "verbose_name_plural": "Баннеры",
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
