# Generated by Django 5.0.6 on 2024-08-23 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banners", "0001_initial"),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="catalog_desktop_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
                verbose_name="Изображение в каталоге (Desktop)",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="catalog_mobile_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
                verbose_name="Изображение в каталоге (Mobile)",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="header_desktop_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
                verbose_name="Изображение в шапке",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="home_desktop_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
                verbose_name="Изображение на главной (Desktop)",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="home_mobile_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
                verbose_name="Изображение на главной (Mobile)",
            ),
        ),
    ]
