# Generated by Django 5.0.6 on 2025-10-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banners", "0002_alter_banner_catalog_desktop_image_and_more"),
        ("images", "0002_alter_image_options_alter_image_alt_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={
                "ordering": ["-created_at", "-pk"],
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
            },
        ),
        migrations.AlterField(
            model_name="banner",
            name="catalog_desktop_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
                verbose_name="Catalog image (Desktop)",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="catalog_mobile_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
                verbose_name="Catalog image (Mobile)",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="date_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="End date"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="date_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Start date"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="header_desktop_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
                verbose_name="Header image (Desktop)",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="home_desktop_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
                verbose_name="Home image (Desktop)",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="home_mobile_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
                verbose_name="Home image (Mobile)",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Status"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="is_on_all_pages",
            field=models.BooleanField(
                default=False, verbose_name="Show on all pages"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="url",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Link"
            ),
        ),
    ]
