# Generated by Django 5.0.6 on 2024-09-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        ("store", "0015_alter_productinshop_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentlyViewed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_viewed",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата просмотра"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_viewed_products",
                        to="customer.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Недавно просмотренный товар",
                "verbose_name_plural": "Недавно просмотренные товары",
                "ordering": ["-date_viewed"],
            },
        ),
        migrations.AddConstraint(
            model_name="recentlyviewed",
            constraint=models.UniqueConstraint(
                fields=("customer", "product"),
                name="unique_customer_recently_product",
            ),
        ),
    ]
