# Generated by Django 5.0.6 on 2025-10-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recently_viewed", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recentlyviewed",
            options={
                "ordering": ["-date_viewed"],
                "verbose_name": "Recently viewed product",
                "verbose_name_plural": "Recently viewed products",
            },
        ),
        migrations.AlterField(
            model_name="recentlyviewed",
            name="date_viewed",
            field=models.DateTimeField(
                auto_now=True, verbose_name="View date"
            ),
        ),
    ]
