# Generated by Django 5.0.6 on 2024-06-07 14:59

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking_index", "0001_initial"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("IN_STOCK", "В наличии"),
                            ("LIMITED", "Ограничен"),
                            ("ON_ORDER", "Под заказ"),
                            ("PENDING", "Ожидается"),
                            ("OUT_OF_STOCK", "Нет в наличии"),
                        ],
                        max_length=50,
                        verbose_name="Код",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Цвет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ствтус товара",
                "verbose_name_plural": "Статусы товара",
                "ordering": ["pk"],
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AddField(
            model_name="product",
            name="_additional_products",
            field=models.ManyToManyField(
                blank=True,
                to="store.product",
                verbose_name="Дополнительные товары",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="bonuses",
            field=models.BooleanField(
                default=False, verbose_name="Возможность получения бонусов"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=8,
                verbose_name="Размер скидки в процентах",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="model",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Модель товара",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="often_search",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ranking_index.rankingindex",
                verbose_name="Индекс частых запросов",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="popular",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ranking_index.rankingindex",
                verbose_name="Индекс популярности",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="publish",
            field=models.BooleanField(
                default=True, verbose_name="Опубликован?"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Количество"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sales",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ranking_index.rankingindex",
                verbose_name="Индекс продаж",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                default=None,
                max_length=255,
                unique=True,
                verbose_name="Артикул",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="youtube_link",
            field=models.URLField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Ссылка на видеообзор",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=9, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Короткое описание"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                to="store.productstatus",
                verbose_name="Статус",
            ),
            preserve_default=False,
        ),
    ]
