# Generated by Django 5.0.6 on 2024-06-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_productstatus_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productstatus",
            name="code",
            field=models.CharField(
                choices=[],
                max_length=50,
                verbose_name="Код",
            ),
        ),
    ]
