# Generated by Django 5.0.6 on 2024-06-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_productstatus_code"),
    ]
    operations = [
        migrations.AlterField(
            model_name="productstatus",
            name="code",
            field=models.CharField(
                choices=[
                    ("IN_STOCK", "В наличии"),
                    ("LIMITED", "Ограниченное количество"),
                    ("ON_ORDER", "Под заказ"),
                    ("PENDING", "Ожидается"),
                    ("OUT_OF_STOCK", "Нет в наличии"),
                ],
                max_length=50,
                verbose_name="Код",
            ),
        ),
    ]
