# Generated by Django 5.0.6 on 2024-06-11 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_productstatus_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Код"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Город",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Улица",
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Дом",
                    ),
                ),
                ("working_from", models.TimeField(verbose_name="Работает с")),
                ("working_to", models.TimeField(verbose_name="Работает до")),
                (
                    "pickup",
                    models.BooleanField(
                        default=True,
                        verbose_name="Есть возможность самовывоза",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "lat",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "long",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Позиция при сортировке",
                    ),
                ),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProductInShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Количество"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_product_in_shops",
                        to="store.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.shop",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в магазине",
                "verbose_name_plural": "Товары в магазинах",
                "ordering": ["-quantity", "shop__pk"],
            },
        ),
    ]
