# Generated by Django 5.0.6 on 2024-06-11 10:48

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("ranking_index", "0001_initial"),
        ("store", "0005_shop_productinshop"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Краткое название",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        image_field=None,
                        max_length=25,
                        null=True,
                        samples=None,
                        verbose_name="Цвет",
                    ),
                ),
                ("object_class", models.CharField(max_length=20)),
                (
                    "active_filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Активные фильтры",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Время последнего обновления",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "background",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="images.image",
                        verbose_name="Фоновое изображение",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="images.image",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="store.catalog",
                        verbose_name="Родительский каталог",
                    ),
                ),
                (
                    "popular",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ranking_index.rankingindex",
                    ),
                ),
            ],
            options={
                "verbose_name": "Каталог",
                "verbose_name_plural": "Каталоги",
                "ordering": ["-popular___index"],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("store.catalog",),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("store.catalog",),
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("store.catalog",),
        ),
        migrations.CreateModel(
            name="FreeTag",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("store.catalog",),
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("store.catalog",),
        ),
        migrations.CreateModel(
            name="Selection",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("store.catalog",),
        ),
        migrations.AddConstraint(
            model_name="catalog",
            constraint=models.UniqueConstraint(
                fields=("slug", "parent"), name="unique_slug_parent"
            ),
        ),
    ]
