# Generated by Django 5.0.6 on 2024-06-12 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking_index", "0001_initial"),
        ("store", "0007_alter_catalog_background_alter_catalog_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=110, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа атрибутов",
                "verbose_name_plural": "Группы атрибутов",
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Значение"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение атрибута",
                "verbose_name_plural": "Значения атрибутов",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "added_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Добавленное название",
                    ),
                ),
                (
                    "measure_unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "visibility_in_filter",
                    models.BooleanField(
                        default=0, verbose_name="Видимость в фильтре"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NUM_INT", "Числовой"),
                            ("NUM_RANGE", "Числовой диапазон"),
                            ("TEXT", "Текстовый"),
                            ("BOOLEAN", "Переключатель"),
                            ("LIST", "Список"),
                            ("SELECT", "Вариативный"),
                        ],
                        max_length=12,
                        verbose_name="Тип атрибута",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attributes",
                        to="store.attributegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Атрибут",
                "verbose_name_plural": "Атрибуты",
            },
        ),
        migrations.CreateModel(
            name="ListingAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=1000, verbose_name="Порядок"
                    ),
                ),
                (
                    "_possible_values",
                    models.ManyToManyField(
                        blank=True,
                        to="store.attributevalue",
                        verbose_name="Возможные значения атрибута",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.attribute",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_attributes",
                        to="store.catalog",
                    ),
                ),
                (
                    "popular",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ranking_index.rankingindex",
                    ),
                ),
            ],
            options={
                "verbose_name": "Атрибут в категории",
                "verbose_name_plural": "Атрибуты в категориях",
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_values",
                    models.ManyToManyField(
                        blank=True,
                        to="store.attributevalue",
                        verbose_name="Значения атрибута",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.attribute",
                        verbose_name="Атрибут",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_attributes",
                        to="store.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Атрибут товара",
                "verbose_name_plural": "Атрибуты товаров",
                "ordering": ["attribute__pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="listingattribute",
            constraint=models.UniqueConstraint(
                fields=("listing", "attribute"),
                name="unique_listing_attribute",
            ),
        ),
        migrations.AddConstraint(
            model_name="productattribute",
            constraint=models.UniqueConstraint(
                fields=("product", "attribute"),
                name="unique_product_attribute",
            ),
        ),
    ]
