# Generated by Django 5.0.6 on 2024-06-12 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_attributegroup_attributevalue_attribute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="_tags",
            field=models.ManyToManyField(
                related_name="_products", to="store.catalog"
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_product_attributes",
                to="store.product",
                verbose_name="Товар",
            ),
        ),
        migrations.CreateModel(
            name="ProductAddService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Настройка", "Настройка"),
                            (
                                "Дополнительная гарантия",
                                "Дополнительная гарантия",
                            ),
                            ("Установка", "Установка"),
                        ],
                        max_length=30,
                        verbose_name="Тип услуги",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название услуги"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="Стоимость услуги",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_services",
                        to="store.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доп. услуга",
                "verbose_name_plural": "Доп. услуги",
                "ordering": ["type", "price"],
            },
        ),
    ]
