# Generated by Django 5.0.6 on 2024-06-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "store",
            "0009_product__tags_alter_productattribute_product_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_date", models.DateField(verbose_name="Дата показа")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар дня",
                "verbose_name_plural": "Товары дня",
            },
        ),
        migrations.AddConstraint(
            model_name="productday",
            constraint=models.UniqueConstraint(
                fields=("product", "show_date"),
                name="unique_product_show_date",
            ),
        ),
    ]
