# Generated by Django 5.0.6 on 2024-06-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(
                default=False, verbose_name="Основное изображение"
            ),
        ),
    ]
