# Generated by Django 5.0.6 on 2024-06-25 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_productimage_is_main"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["-is_main", "-pk"],
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="_attributes",
            field=models.ManyToManyField(
                through="store.ProductAttribute", to="store.attribute"
            ),
        ),
        migrations.AlterField(
            model_name="listingattribute",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_listing_attributes",
                to="store.catalog",
            ),
        ),
    ]
