# Generated by Django 5.0.6 on 2024-08-23 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        (
            "store",
            "0013_alter_productimage_options_product__attributes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="background",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
                verbose_name="Фоновое изображение",
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
                verbose_name="Изображение",
            ),
        ),
    ]
