# Generated by Django 5.0.6 on 2024-09-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_alter_catalog_background_alter_catalog_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productinshop",
            options={
                "ordering": ["shop__order"],
                "verbose_name": "Товар в магазине",
                "verbose_name_plural": "Товары в магазинах",
            },
        ),
    ]
