# Generated by Django 5.0.6 on 2024-10-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_alter_productinshop_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="postcode",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Почтовый индекс",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Регион"
            ),
        ),
    ]
