# Generated by Django 5.0.6 on 2024-12-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_shop_postcode_shop_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
