# Generated by Django 5.0.6 on 2024-12-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_alter_catalog_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
