# Generated by Django 5.0.6 on 2024-12-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_alter_catalog_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
