# Generated by Django 5.0.6 on 2024-12-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_created_at"),
        ("store", "0023_productreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="_reviews",
            field=models.ManyToManyField(
                through="store.ProductReview", to="reviews.review"
            ),
        ),
    ]
