# Generated by Django 5.0.6 on 2025-04-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_product__reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalog",
            name="_additional_products",
            field=models.ManyToManyField(
                blank=True,
                to="store.product",
                verbose_name="Дополнительные товары в категории",
            ),
        ),
    ]
