# Generated by Django 5.0.6 on 2025-05-02 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_catalog__additional_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Позиция при сортировке",
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="shop",
            name="city_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.city",
                verbose_name="Город",
            ),
        ),
    ]
