# Generated by Django 5.0.6 on 2025-05-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0026_city_shop_city_obj"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["order", "pk"],
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
    ]
