# Generated by Django 5.0.6 on 2025-06-25 17:24

from django.db import migrations, models


def set_code2_for_existing_shops(apps, schema_editor):
    Shop = apps.get_model("store", "Shop")
    # здесь ключ — это id магазина, значение — то, что вы хотите записать в code2
    mapping = {
        1: "Магазин г.Донецк пр. Ильича, 44",
        2: "Магазин г.Донецк ул.230-й стр.дивизии, 2б",
        3: "Магазин г.Донецк, пр.Мира, 9",
        4: "Магазин г.Донецк, пл.Коммунаров, 1",
        5: "Магазин г.Донецк, ул. Петровского,138",
        6: "Магазин г.Макеевка, ул.Московская 2",
        7: "Магазин г.Мариуполь, ул.Куприна, 10",
        8: "Магазин г.Горловка, пр. Победы,36",
        9: "Магазин г.Енакиево, пр. Ленина, д. 87-б",
        10: "ДЦ СКЛАД =ЭЛ= Главный склад",
        11: "Магазин г.Мариуполь, пр. Металлургов, 100",
        13: "Магазин г.Шахтерск ул.Крупской, 1",
        14: "Магазин г.Мелитополь,пр.Б.Хмельницкого,17",
    }

    # Пробегаем по всем магазинам
    for shop in Shop.objects.all():
        if shop.pk in mapping:
            shop.code2 = mapping[shop.pk]
        else:
            # для тех, кого нет в mapping, делаем fallback на старый code
            shop.code2 = shop.code
        shop.save(update_fields=["code2"])


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0027_alter_city_options"),
    ]

    operations = [
        # 1) добавляем поле code2, позволяя NULL и без unique
        migrations.AddField(
            model_name="shop",
            name="code2",
            field=models.CharField(
                max_length=100,
                null=True,
                blank=True,
                verbose_name="Код2",
            ),
        ),
        # 2) заполняем его для существующих записей
        migrations.RunPython(set_code2_for_existing_shops),
        # 3) теперь делаем code2 обязательным и уникальным
        migrations.AlterField(
            model_name="shop",
            name="code2",
            field=models.CharField(
                max_length=100,
                unique=True,
                verbose_name="Код2",
            ),
        ),
    ]
