# Generated by Django 5.0.6 on 2025-07-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0028_shop_code2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="status",
        ),
        migrations.DeleteModel(
            name="ProductStatus",
        ),
    ]
