# Generated by Django 5.0.6 on 2025-08-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0029_remove_product_status_delete_productstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                verbose_name="Себестоимость",
            ),
        ),
    ]
