# Generated by Django 5.0.6 on 2025-09-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0030_product_cost_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="schedule_list",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                verbose_name="График работы в виде списка строк",
            ),
        ),
    ]
