# Generated by Django 5.0.6 on 2025-10-14 14:58

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_alter_image_options_alter_image_alt_and_more"),
        ("ranking_index", "0002_alter_rankingindex__index_and_more"),
        (
            "reviews",
            "0007_alter_review_options_alter_review_advantages_and_more",
        ),
        ("store", "0031_shop_schedule_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attribute",
            options={
                "verbose_name": "Attribute",
                "verbose_name_plural": "Attributes",
            },
        ),
        migrations.AlterModelOptions(
            name="attributegroup",
            options={
                "verbose_name": "Attribute group",
                "verbose_name_plural": "Attribute groups",
            },
        ),
        migrations.AlterModelOptions(
            name="attributevalue",
            options={
                "ordering": ["slug"],
                "verbose_name": "Attribute value",
                "verbose_name_plural": "Attribute values",
            },
        ),
        migrations.AlterModelOptions(
            name="catalog",
            options={
                "ordering": ["-popular___index"],
                "verbose_name": "Catalog",
                "verbose_name_plural": "Catalogs",
            },
        ),
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["order", "pk"],
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.AlterModelOptions(
            name="listingattribute",
            options={
                "verbose_name": "Attribute in category",
                "verbose_name_plural": "Attributes in categories",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterModelOptions(
            name="productaddservice",
            options={
                "ordering": ["type", "price"],
                "verbose_name": "Additional service",
                "verbose_name_plural": "Additional services",
            },
        ),
        migrations.AlterModelOptions(
            name="productattribute",
            options={
                "ordering": ["attribute__pk"],
                "verbose_name": "Product attribute",
                "verbose_name_plural": "Product attributes",
            },
        ),
        migrations.AlterModelOptions(
            name="productday",
            options={
                "verbose_name": "Product of the day",
                "verbose_name_plural": "Products of the day",
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["-is_main", "-pk"],
                "verbose_name": "Product image",
                "verbose_name_plural": "Product images",
            },
        ),
        migrations.AlterModelOptions(
            name="productinshop",
            options={
                "ordering": ["shop__order"],
                "verbose_name": "Product in shop",
                "verbose_name_plural": "Products in shops",
            },
        ),
        migrations.AlterModelOptions(
            name="productreview",
            options={
                "ordering": ["-review__created_at"],
                "verbose_name": "Product review",
                "verbose_name_plural": "Product reviews",
            },
        ),
        migrations.AlterModelOptions(
            name="shop",
            options={
                "ordering": ["order"],
                "verbose_name": "Shop",
                "verbose_name_plural": "Shops",
            },
        ),
        migrations.AlterField(
            model_name="attribute",
            name="added_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Additional name",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="measure_unit",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Unit of measure",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="type",
            field=models.CharField(
                choices=[
                    ("NUM_INT", "Numeric"),
                    ("NUM_RANGE", "Numeric range"),
                    ("TEXT", "Text"),
                    ("BOOLEAN", "Switch"),
                    ("LIST", "List"),
                    ("SELECT", "Selectable"),
                ],
                max_length=12,
                verbose_name="Attribute type",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="visibility_in_filter",
            field=models.BooleanField(
                default=0, verbose_name="Visible in filter"
            ),
        ),
        migrations.AlterField(
            model_name="attributegroup",
            name="name",
            field=models.CharField(
                max_length=110, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="attributevalue",
            name="value",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Value"
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="_additional_products",
            field=models.ManyToManyField(
                blank=True,
                to="store.product",
                verbose_name="Additional products in category",
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="active_filters",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="Active filters",
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="background",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
                verbose_name="Background image",
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="icon",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Icon"
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="store.catalog",
                verbose_name="Parent catalog",
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="short_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Short name",
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="order",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Sort order position"
            ),
        ),
        migrations.AlterField(
            model_name="listingattribute",
            name="_possible_values",
            field=models.ManyToManyField(
                blank=True,
                to="store.attributevalue",
                verbose_name="Possible attribute values",
            ),
        ),
        migrations.AlterField(
            model_name="listingattribute",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=1000, verbose_name="Order"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="_additional_products",
            field=models.ManyToManyField(
                blank=True,
                to="store.product",
                verbose_name="Additional products",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="bonuses",
            field=models.BooleanField(
                default=False, verbose_name="Bonuses available"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                verbose_name="Cost price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=8,
                verbose_name="Discount percent",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Model"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="often_search",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ranking_index.rankingindex",
                verbose_name="Search frequency index",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="popular",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ranking_index.rankingindex",
                verbose_name="Popularity index",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=9, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="publish",
            field=models.BooleanField(default=True, verbose_name="Published?"),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Quantity"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sales",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ranking_index.rankingindex",
                verbose_name="Sales index",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Short description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="SKU"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="youtube_link",
            field=models.URLField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Video review link",
            ),
        ),
        migrations.AlterField(
            model_name="productaddservice",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Service name"
            ),
        ),
        migrations.AlterField(
            model_name="productaddservice",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                verbose_name="Service price",
            ),
        ),
        migrations.AlterField(
            model_name="productaddservice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_services",
                to="store.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productaddservice",
            name="type",
            field=models.CharField(
                choices=[
                    ("Setting up", "Setup"),
                    ("Extended warranty", "Extended warranty"),
                    ("Installation", "Installation"),
                ],
                max_length=30,
                verbose_name="Service type",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="_values",
            field=models.ManyToManyField(
                blank=True,
                to="store.attributevalue",
                verbose_name="Attribute values",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.attribute",
                verbose_name="Attribute",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_product_attributes",
                to="store.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productday",
            name="show_date",
            field=models.DateField(verbose_name="Show date"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(
                default=False, verbose_name="Main image"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_images",
                to="store.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productinshop",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_product_in_shops",
                to="store.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productinshop",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Quantity"
            ),
        ),
        migrations.AlterField(
            model_name="productinshop",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.shop",
                verbose_name="Shop",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reviews.review",
                verbose_name="Review",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="city_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.city",
                verbose_name="City object",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="code",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Code"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="code2",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Code2"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="house",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="House"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="lat",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="long",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Longitude"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="order",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Display order"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="pickup",
            field=models.BooleanField(
                default=True, verbose_name="Pickup available"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="postcode",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Postcode"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Region"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="schedule_list",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                verbose_name="Work schedule as list of strings",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="street",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Street"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="working_from",
            field=models.TimeField(verbose_name="Opens at"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="working_to",
            field=models.TimeField(verbose_name="Closes at"),
        ),
    ]
