# Generated by Django 5.0.6 on 2024-09-03 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0015_alter_productinshop_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="ID сессии"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "date_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Город",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Улица",
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Дом",
                    ),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Квартира",
                    ),
                ),
                (
                    "vk",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ссылка на ВК",
                    ),
                ),
                (
                    "viber",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ссылка на Viber",
                    ),
                ),
                (
                    "telegram",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ссылка на Telegram",
                    ),
                ),
                (
                    "yandex_uids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Yandex ClientIDs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Покупатель",
                "verbose_name_plural": "Покупатели",
            },
        ),
        migrations.CreateModel(
            name="CustomerSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_start",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время начала"
                    ),
                ),
                (
                    "date_last_activity",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Дата и время последней активности",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=1, verbose_name="Статус"),
                ),
                (
                    "traffic_source",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Источник трафика",
                    ),
                ),
                (
                    "_visited_products",
                    models.ManyToManyField(blank=True, to="store.product"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_sessions",
                        to="customer.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_last_activity"],
            },
        ),
    ]
