# Generated by Django 5.0.6 on 2024-09-04 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cartproductaddservice_service"),
        ("customer", "0002_customer_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="cart",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="cart.cart",
                verbose_name="Корзина",
            ),
            preserve_default=False,
        ),
    ]
