# Generated by Django 5.0.6 on 2024-09-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_alter_customer_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="email",
            new_name="contact_email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="telegram",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="viber",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="vk",
        ),
    ]
