# Generated by Django 5.0.6 on 2024-09-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_rename_email_customer_contact_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="phone",
            new_name="contact_phone",
        ),
    ]
