# Generated by Django 5.0.6 on 2024-09-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_rename_phone_customer_contact_phone"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="_orders",
            field=models.ManyToManyField(blank=True, to="orders.order"),
        ),
    ]
