# Generated by Django 5.0.6 on 2024-11-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_customer__orders"),
        ("orders", "0003_order_spent_bonuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="_orders",
            field=models.ManyToManyField(
                blank=True, related_name="customer", to="orders.order"
            ),
        ),
    ]
