# Generated by Django 5.0.6 on 2025-05-02 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_alter_customer__orders"),
        ("store", "0027_alter_city_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="city_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.city",
                verbose_name="Город",
            ),
        ),
    ]
