# Generated by Django 5.0.6 on 2025-07-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_customer_city_obj"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomerSession",
        ),
    ]
