# Generated by Django 5.0.6 on 2025-07-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0012_delete_customersession"),
        ("orders", "0008_populate_customer_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="_orders",
        ),
    ]
