# Generated by Django 5.0.6 on 2025-07-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0013_remove_customer__orders"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="contact_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="contact_phone",
            new_name="phone",
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                null=True,
                blank=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                max_length=20,
                unique=True,
                null=True,
                blank=True,
                verbose_name="Телефон",
            ),
        ),
    ]
