# Generated by Django 5.0.6 on 2025-07-15 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cartproductaddservice_service"),
        ("customer", "0016_customer_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="cart",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer",
                to="cart.cart",
                verbose_name="Корзина",
            ),
        ),
    ]
