# Generated by Django 5.0.6 on 2025-10-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cart_options_alter_cartproduct_options_and_more"),
        ("customer", "0017_alter_customer_cart"),
        ("store", "0031_shop_schedule_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.AlterField(
            model_name="customer",
            name="apartment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Apartment"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="cart",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer",
                to="cart.cart",
                verbose_name="Cart",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="city_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.city",
                verbose_name="City (object)",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="date_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date of birth"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="First name",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="house",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="House"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="patronymic",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Middle name",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Phone",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="session_id",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Session ID"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="street",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Street"
            ),
        ),
    ]
