# Generated by Django 5.0.6 on 2025-10-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "link",
                    models.CharField(max_length=255, verbose_name="Ссылка"),
                ),
            ],
            options={
                "verbose_name": "Короткая ссылка",
                "verbose_name_plural": "Короткие ссылки",
                "ordering": ["-pk"],
            },
        ),
    ]
