# Generated by Django 5.0.6 on 2025-10-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("short_links", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shortlink",
            options={
                "ordering": ["-pk"],
                "verbose_name": "Short link",
                "verbose_name_plural": "Short links",
            },
        ),
        migrations.AlterField(
            model_name="shortlink",
            name="link",
            field=models.CharField(max_length=255, verbose_name="Link"),
        ),
    ]
