# Generated by Django 5.0.6 on 2024-06-07 11:57

from django.db import migrations, models

import ranking_index.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RankingIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_index",
                    models.DecimalField(
                        decimal_places=5,
                        default=0,
                        max_digits=15,
                        verbose_name="Индекс",
                    ),
                ),
                (
                    "_index_counter",
                    models.JSONField(
                        blank=True,
                        default=ranking_index.models.get_default_counter_dict,
                        verbose_name="Счётчик",
                    ),
                ),
            ],
        ),
    ]
