# Generated by Django 5.0.6 on 2025-10-14 14:58

from django.db import migrations, models

import ranking_index.models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking_index", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankingindex",
            name="_index",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=15,
                verbose_name="Index",
            ),
        ),
        migrations.AlterField(
            model_name="rankingindex",
            name="_index_counter",
            field=models.JSONField(
                blank=True,
                default=ranking_index.models.get_default_counter_dict,
                verbose_name="Counter",
            ),
        ),
    ]
