# Generated by Django 5.0.6 on 2024-10-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0015_alter_productinshop_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "is_publish",
                    models.BooleanField(
                        default=1, verbose_name="Опубликована?"
                    ),
                ),
                (
                    "likes",
                    models.IntegerField(
                        default=0, verbose_name="Количество лайков"
                    ),
                ),
                (
                    "dislikes",
                    models.IntegerField(
                        default=0, verbose_name="Количество дизлайков"
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
                (
                    "_products",
                    models.ManyToManyField(
                        blank=True,
                        to="store.product",
                        verbose_name="Товары в статье",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
