# Generated by Django 5.0.6 on 2024-10-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        ("images", "0001_initial"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="_reviews",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="reviews.review",
                verbose_name="Отзывы",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
                verbose_name="Изображение",
            ),
        ),
    ]
