# Generated by Django 5.0.6 on 2024-10-02 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
        ("customer", "0006_customer__orders"),
        ("store", "0015_alter_productinshop_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="store.product",
                verbose_name="Товары в статье",
            ),
        ),
        migrations.CreateModel(
            name="ArticleCustomerReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_like",
                    models.BooleanField(default=True, verbose_name="Лайк?"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.article",
                        verbose_name="Статья",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                        verbose_name="Покупатель",
                    ),
                ),
            ],
            options={
                "unique_together": {("customer", "article")},
            },
        ),
    ]
