# Generated by Django 5.0.6 on 2024-11-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article__products_articlecustomerreaction"),
        ("store", "0016_shop_postcode_shop_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                to="store.product",
                verbose_name="Товары в статье",
            ),
        ),
    ]
