# Generated by Django 5.0.6 on 2024-11-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_article_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата добавления"
            ),
        ),
    ]
