# Generated by Django 5.0.6 on 2024-11-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_article_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(verbose_name="Дата добавления"),
        ),
    ]
