# Generated by Django 5.0.6 on 2025-10-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_article_created_at"),
        ("customer", "0017_alter_customer_cart"),
        ("images", "0002_alter_image_options_alter_image_alt_and_more"),
        ("reviews", "0006_alter_review_created_at"),
        ("store", "0031_shop_schedule_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                to="store.product",
                verbose_name="Products in article",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="_reviews",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="reviews.review",
                verbose_name="Reviews",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="dislikes",
            field=models.IntegerField(
                default=0, verbose_name="Dislikes count"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="is_publish",
            field=models.BooleanField(default=1, verbose_name="Published?"),
        ),
        migrations.AlterField(
            model_name="article",
            name="likes",
            field=models.IntegerField(default=0, verbose_name="Likes count"),
        ),
        migrations.AlterField(
            model_name="article",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="article",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Views count"),
        ),
        migrations.AlterField(
            model_name="articlecustomerreaction",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.article",
                verbose_name="Article",
            ),
        ),
        migrations.AlterField(
            model_name="articlecustomerreaction",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="articlecustomerreaction",
            name="is_like",
            field=models.BooleanField(default=True, verbose_name="Is like?"),
        ),
    ]
