# Generated by Django 5.0.6 on 2025-10-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "ordering": ["id"],
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.AlterField(
            model_name="image",
            name="alt",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Alt text"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Image"),
        ),
    ]
