# Generated by Django 5.0.6 on 2024-10-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0006_customer__orders"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Имя"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                ("rating", models.SmallIntegerField(verbose_name="Оценка")),
                (
                    "comment",
                    models.TextField(
                        max_length=500, verbose_name="Комментарий"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "advantages",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Преимущества",
                    ),
                ),
                (
                    "disadvantages",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Недостатки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "is_publish",
                    models.BooleanField(
                        default=0, verbose_name="Опубликована?"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                        verbose_name="Покупатель",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_replies",
                        to="reviews.review",
                        verbose_name="Ответ на",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
    ]
