# Generated by Django 5.0.6 on 2024-12-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(verbose_name="Дата публикации"),
        ),
    ]
