# Generated by Django 5.0.6 on 2024-12-19 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="email",
        ),
    ]
