# Generated by Django 5.0.6 on 2024-12-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_remove_review_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(verbose_name="Дата публикации"),
        ),
    ]
