# Generated by Django 5.0.6 on 2025-10-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customer",
            "0018_alter_customer_options_alter_customer_apartment_and_more",
        ),
        ("reviews", "0006_alter_review_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.AlterField(
            model_name="review",
            name="advantages",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Advantages",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(max_length=500, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Publication date"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="disadvantages",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Disadvantages",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="review",
            name="is_publish",
            field=models.BooleanField(default=0, verbose_name="Published?"),
        ),
        migrations.AlterField(
            model_name="review",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.SmallIntegerField(verbose_name="Rating"),
        ),
        migrations.AlterField(
            model_name="review",
            name="reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_replies",
                to="reviews.review",
                verbose_name="Reply to",
            ),
        ),
    ]
