# Generated by Django 5.0.6 on 2024-09-06 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0005_rename_phone_customer_contact_phone"),
        ("store", "0015_alter_productinshop_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompareProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_compare_products",
                        to="customer.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в сравнении",
                "verbose_name_plural": "Товары в сравнении",
                "ordering": ["date_added"],
            },
        ),
        migrations.AddConstraint(
            model_name="compareproduct",
            constraint=models.UniqueConstraint(
                fields=("customer", "product"),
                name="unique_customer_compare_product",
            ),
        ),
    ]
