# Generated by Django 5.0.6 on 2025-10-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compare", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compareproduct",
            options={
                "ordering": ["date_added"],
                "verbose_name": "Compared product",
                "verbose_name_plural": "Compared products",
            },
        ),
        migrations.AlterField(
            model_name="compareproduct",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date added"
            ),
        ),
    ]
