# Generated by Django 5.0.6 on 2024-09-04 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("store", "0015_alter_productinshop_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproductaddservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.productaddservice",
                verbose_name="Доп. услуга",
            ),
        ),
    ]
