# Generated by Django 5.0.6 on 2025-10-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cartproductaddservice_service"),
        ("store", "0031_shop_schedule_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Cart", "verbose_name_plural": "Carts"},
        ),
        migrations.AlterModelOptions(
            name="cartproduct",
            options={
                "ordering": ["date_added"],
                "verbose_name": "Cart item",
                "verbose_name_plural": "Cart items",
            },
        ),
        migrations.AlterField(
            model_name="cart",
            name="_products",
            field=models.ManyToManyField(
                through="cart.CartProduct",
                to="store.product",
                verbose_name="Products in cart",
            ),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="_services",
            field=models.ManyToManyField(
                through="cart.CartProductAddService",
                to="store.productaddservice",
                verbose_name="Add-on services",
            ),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_cart_products",
                to="cart.cart",
                verbose_name="Cart",
            ),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date added"
            ),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="cartproductaddservice",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Selected?"),
        ),
        migrations.AlterField(
            model_name="cartproductaddservice",
            name="cart_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_cart_product_add_services",
                to="cart.cartproduct",
                verbose_name="Cart item",
            ),
        ),
        migrations.AlterField(
            model_name="cartproductaddservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.productaddservice",
                verbose_name="Add-on service",
            ),
        ),
    ]
