# Generated by Django 5.0.6 on 2024-06-26 13:32

import django.db.models.deletion
import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "store",
            "0013_alter_productimage_options_product__attributes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SimplePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_h1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="H1",
                    ),
                ),
                (
                    "_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "head",
                    models.TextField(
                        blank=True, null=True, verbose_name="Head"
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Robots",
                    ),
                ),
                (
                    "_rich_content",
                    django_editorjs_fields.fields.EditorJsJSONField(
                        blank=True, null=True
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Простая страница",
                "verbose_name_plural": "Простые страницы",
            },
        ),
        migrations.CreateModel(
            name="CatalogPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_h1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="H1",
                    ),
                ),
                (
                    "_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "head",
                    models.TextField(
                        blank=True, null=True, verbose_name="Head"
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Robots",
                    ),
                ),
                (
                    "_rich_content",
                    django_editorjs_fields.fields.EditorJsJSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "catalog",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_catalog_page",
                        to="store.catalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница каталога",
                "verbose_name_plural": "Страницы каталогов",
            },
        ),
        migrations.CreateModel(
            name="ProductPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_h1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="H1",
                    ),
                ),
                (
                    "_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "head",
                    models.TextField(
                        blank=True, null=True, verbose_name="Head"
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Robots",
                    ),
                ),
                (
                    "_rich_content",
                    django_editorjs_fields.fields.EditorJsJSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_product_page",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница товара",
                "verbose_name_plural": "Страницы товаров",
            },
        ),
    ]
