# Generated by Django 5.0.6 on 2024-10-02 13:21

import django.db.models.deletion
import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        ("web_pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_h1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="H1",
                    ),
                ),
                (
                    "_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "head",
                    models.TextField(
                        blank=True, null=True, verbose_name="Head"
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Robots",
                    ),
                ),
                (
                    "_rich_content",
                    django_editorjs_fields.fields.EditorJsJSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_article_page",
                        to="blog.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница статьи",
                "verbose_name_plural": "Страницы статей",
            },
        ),
    ]
