# Generated by Django 5.0.6 on 2025-10-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0002_articlepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articlepage",
            options={
                "verbose_name": "Article Page",
                "verbose_name_plural": "Article Pages",
            },
        ),
        migrations.AlterModelOptions(
            name="catalogpage",
            options={
                "verbose_name": "Catalog Page",
                "verbose_name_plural": "Catalog Pages",
            },
        ),
        migrations.AlterModelOptions(
            name="productpage",
            options={
                "verbose_name": "Product Page",
                "verbose_name_plural": "Product Pages",
            },
        ),
        migrations.AlterModelOptions(
            name="simplepage",
            options={
                "verbose_name": "Simple Page",
                "verbose_name_plural": "Simple Pages",
            },
        ),
    ]
