# Generated by Django 5.0.6 on 2024-06-25 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ranking_index", "0001_initial"),
        (
            "store",
            "0013_alter_productimage_options_product__attributes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Текст"
                    ),
                ),
                (
                    "is_publish",
                    models.BooleanField(
                        default=True, verbose_name="Опубликован?"
                    ),
                ),
                (
                    "is_moderation",
                    models.BooleanField(
                        default=False, verbose_name="Утверждён?"
                    ),
                ),
                (
                    "count_requests",
                    models.IntegerField(
                        default=1, verbose_name="Количество обращений"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "catalog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="store.catalog",
                    ),
                ),
                (
                    "popular",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ranking_index.rankingindex",
                        verbose_name="Индекс популярности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поисковый запрос",
                "verbose_name_plural": "Поисковые запросы",
                "ordering": ["-pk"],
            },
        ),
    ]
