# Generated by Django 5.0.6 on 2024-06-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchquery",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Поисковый запрос",
                "verbose_name_plural": "Поисковые запросы",
            },
        ),
    ]
