# Generated by Django 5.0.6 on 2025-10-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking_index", "0002_alter_rankingindex__index_and_more"),
        ("search", "0002_alter_searchquery_options"),
        (
            "store",
            "0032_alter_attribute_options_alter_attributegroup_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchquery",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Search query",
                "verbose_name_plural": "Search queries",
            },
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="catalog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="store.catalog",
                verbose_name="Catalog",
            ),
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="count_requests",
            field=models.IntegerField(
                default=1, verbose_name="Number of requests"
            ),
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="is_moderation",
            field=models.BooleanField(
                default=False, verbose_name="Is approved?"
            ),
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="is_publish",
            field=models.BooleanField(
                default=True, verbose_name="Is published?"
            ),
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="popular",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ranking_index.rankingindex",
                verbose_name="Popularity index",
            ),
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="text",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Text"
            ),
        ),
    ]
