# Generated by Django 5.0.6 on 2024-09-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_info",
                    models.JSONField(
                        default=dict, verbose_name="Информация о клиенте"
                    ),
                ),
                (
                    "content",
                    models.JSONField(default=dict, verbose_name="Содержание"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CART", "Корзина"),
                            ("ONE_CLICK", "Купить в 1 клик"),
                            ("CALL", "Телефонный звонок"),
                        ],
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "reception_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DELIVERY", "Доставка"),
                            ("PICKUP", "Самовывоз"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Способ получения",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новый"),
                            ("PROCESSED", "Обрабатывается"),
                            ("PAID", "Оплачен"),
                            ("COMPLETED", "Завершен"),
                            ("CANCELED", "Отменён"),
                        ],
                        default="NEW",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Город",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Улица",
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Дом",
                    ),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Квартира",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-date_added"],
            },
        ),
    ]
