# Generated by Django 5.0.6 on 2024-10-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("store", "0016_shop_postcode_shop_region"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.RenameField(
            model_name="order",
            old_name="date_added",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="order",
            name="is_callback",
            field=models.BooleanField(
                default=False, verbose_name="Обратный звонок"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="store.shop",
                verbose_name="Магазин",
            ),
        ),
    ]
