# Generated by Django 5.0.6 on 2024-10-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="spent_bonuses",
            field=models.IntegerField(
                default=0, verbose_name="Бонусов потрачено"
            ),
        ),
    ]
