# Generated by Django 5.0.6 on 2024-12-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_spent_bonuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(verbose_name="Дата добавления"),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
