# Generated by Django 5.0.6 on 2024-12-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_created_at_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата добавления"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
