# Generated by Django 5.0.6 on 2024-12-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_created_at_alter_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("CASH", "Наличными"), ("CARD", "Оплата картой")],
                max_length=16,
                null=True,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
