# Generated by Django 5.0.6 on 2025-07-08 18:09

from django.db import migrations


def migrate_orders_customer(apps, schema_editor):
    Customer = apps.get_model("customer", "Customer")
    Order = apps.get_model("orders", "Order")
    through_table = Customer._meta.get_field("_orders").remote_field.through

    # Создаём маппинг order_id -> customer_id из M2M
    order_to_customer = {
        link.order_id: link.customer_id for link in through_table.objects.all()
    }

    for order in Order.objects.all():
        customer_id = order_to_customer.get(order.id)

        if customer_id:
            # Есть связь через M2M
            order.customer_id = customer_id
            order.save(update_fields=["customer"])
            continue

        # Пробуем найти по session_id
        session_id = order.customer_info.get("session_id")
        if session_id:
            customer = Customer.objects.filter(session_id=session_id).first()
            if customer:
                order.customer = customer
                order.save(update_fields=["customer"])
                continue


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_customer"),
    ]

    operations = [
        migrations.RunPython(
            migrate_orders_customer, reverse_code=migrations.RunPython.noop
        ),
    ]
