# Generated by Django 5.0.6 on 2025-07-08 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_populate_customer_field"),
        ("customer", "0013_remove_customer__orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_orders",
                to="customer.customer",
                verbose_name="Покупатель",
            ),
        ),
    ]
