# Generated by Django 5.0.6 on 2025-07-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="content_for_receipt",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="Содержание для формирования чека",
            ),
        ),
    ]
