# Generated by Django 5.0.6 on 2025-10-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customer",
            "0018_alter_customer_options_alter_customer_apartment_and_more",
        ),
        ("orders", "0010_order_content_for_receipt"),
        (
            "store",
            "0032_alter_attribute_options_alter_attributegroup_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="apartment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Apartment"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Comment"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="content",
            field=models.JSONField(default=dict, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="order",
            name="content_for_receipt",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Content for receipt"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_orders",
                to="customer.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_info",
            field=models.JSONField(default=dict, verbose_name="Customer info"),
        ),
        migrations.AlterField(
            model_name="order",
            name="house",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="House"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_callback",
            field=models.BooleanField(default=False, verbose_name="Callback"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("CASH", "Cash"), ("CARD", "Card")],
                max_length=16,
                null=True,
                verbose_name="Payment method",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="reception_method",
            field=models.CharField(
                blank=True,
                choices=[("DELIVERY", "Delivery"), ("PICKUP", "Pickup")],
                max_length=16,
                null=True,
                verbose_name="Reception method",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="store.shop",
                verbose_name="Shop",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="spent_bonuses",
            field=models.IntegerField(default=0, verbose_name="Spent bonuses"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("PROCESSED", "Processing"),
                    ("PAID", "Paid"),
                    ("COMPLETED", "Completed"),
                    ("CANCELED", "Canceled"),
                ],
                default="NEW",
                max_length=16,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="street",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Street"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="type",
            field=models.CharField(
                choices=[
                    ("CART", "Cart"),
                    ("ONE_CLICK", "One-click purchase"),
                    ("CALL", "Phone call"),
                ],
                max_length=16,
                verbose_name="Type",
            ),
        ),
    ]
