# Generated by Django 5.0.6 on 2024-12-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0024_product__reviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagImporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название"),
                ),
                (
                    "items_list",
                    models.JSONField(
                        default=list, verbose_name="Список артикулов"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "date_start",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата начала показа",
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата завершение показа",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=False, verbose_name="Активен"),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="+", to="store.catalog"
                    ),
                ),
            ],
            options={
                "verbose_name": "Импортер тегов",
                "verbose_name_plural": "Импортеры тегов",
                "ordering": ["-created_at"],
            },
        ),
    ]
