# Generated by Django 5.0.6 on 2025-10-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags_importers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tagimporter",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Tag importer",
                "verbose_name_plural": "Tag importers",
            },
        ),
        migrations.AlterField(
            model_name="tagimporter",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="tagimporter",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date added"
            ),
        ),
        migrations.AlterField(
            model_name="tagimporter",
            name="date_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="End date"
            ),
        ),
        migrations.AlterField(
            model_name="tagimporter",
            name="date_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Start date"
            ),
        ),
        migrations.AlterField(
            model_name="tagimporter",
            name="items_list",
            field=models.JSONField(default=list, verbose_name="List of SKUs"),
        ),
        migrations.AlterField(
            model_name="tagimporter",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
    ]
